- name: Add an Ansible Tower inventory to a Google Cloud DNS zone
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Add DNS record for {{ inventory_hostname }}.{{ zone }} 
      gcdns_record:
        record: "{{ inventory_hostname }}.{{ zone }}"
        zone: "{{ zone }}"
        type: A
        value: "{{ hostvars[inventory_hostname].get('ansible_ssh_host') }}"
        overwrite: true
      when: hostvars[inventory_hostname].get('gce_status')  == "RUNNING"
      delegate_to: localhost
      register: record

    - name: Remove DNS record for {{ inventory_hostname }}.{{ zone }}
      gcdns_record:
        record: "{{ inventory_hostname }}.{{ zone }}"
        zone: "{{ zone }}"
        type: A
        state: absent
        overwrite: true
      when: hostvars[inventory_hostname].get('gce_status') not "RUNNING"
      delegate_to: localhost
      register: record


    - name: debug
      debug:
        var: record
        verbosity: 1
