- name: Add an Ansible Tower inventory to a Google Cloud DNS zone
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Add DNS record for {{ inventory_hostname }}.{{ zone }} 
      local_action:
        module: gcdns_record
        record: "{{ inventory_hostname }}.{{ zone }}"
        zone: "{{ zone }}"
        type: A
        value: "{{ hostvars[inventory_hostname].get('ansible_ssh_host') }}"
        overwrite: true
      delegate_to: localhost
      register: record

    - name: debug
      local_action:
        module: debug
        var: record
        verbosity: 2
