- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Launch instances
      gce:
        instance_names: "{{ instance_names }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        metadata: '{ "diskSizeGb": "20" }'
