- name: Create instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    machine_type: n1-standard-1
    image: centos-7

  tasks:
    - name: Launch instances
      gce:
        instance_names: "{{ instance_names }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        metadata: '{ "diskSizeGb": "20" }'
