- name: Destroy instances
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Destroy instances
      gce:
        instance_names: "{{ instance_names }}"
        state: deleted
