---
- name: patch various Linux hosts with appropriate package manager
  hosts: all
  tasks:

  - name: upgrade all packages with yum
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

  - name: upgrade all packages with dnf
    dnf:
      name: '*'
      state: latest
    when: ansible_distribution == 'Fedora'

  - name: upgrade all packages with apt
    apt: 
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
