---
- name: patch various Linux hosts with appropriate package manager
  hosts: all
  tasks:

  - name: upgrade all packages with yum on RHEL
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

  - name: upgrade all packages with dnf on Fedora
    dnf:
      name: '*'
      state: latest
    when: ansible_distribution == 'Fedora'

  - name: upgrade all packages with apt after refreshing on Debian
    apt: 
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == 'Debian' 
