- name: Shutdown all GCE instances unless limited
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Shutdown {{ inventory_hostname }}
      gce:
        instance_names: "{{ inventory_hostname }}"
        state: stopped
      delegate_to: localhost
      register: record

    - name: debug
      debug:
        var: record
        verbosity: 1
